name: Daily Sync Private to Public

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 04:00 UTC (07:00 in Türkiye)

jobs:
  bulk-sync:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the public repository
      - name: Checkout public repo
        uses: actions/checkout@v3
        with:
          repository: mbartudgn/harvard-cs50-projects
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          ref: main
          path: public

      # 2) Checkout the private repository (fetch all branches)
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: me50/mbartudgn
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          fetch-depth: 0
          path: private

      # 3) List all branches except main
      - name: List private branches
        id: list_branches
        run: |
          cd private
          git fetch --all
          branches=$(git branch -r \
            | grep -v 'HEAD' \
            | grep -v 'origin/main' \
            | sed 's|origin/||' \
            | tr '\n' ' ')
          echo "branches=$branches" >> $GITHUB_OUTPUT

      # 4) For each branch, copy its root files into incoming/<filename>/ folder
      - name: Copy private files into incoming/
        run: |
          cd private
          for br in ${{ steps.list_branches.outputs.branches }}; do
            echo ">>> Syncing branch: $br"
            git checkout "$br"
            for file in *; do
              if [ -f "$file" ]; then
                folder="${file%.*}"
                mkdir -p "../public/incoming/$folder"
                cp -u "$file" "../public/incoming/$folder/"
              fi
            done
          done

      # 5) Commit and push only the incoming/ folder
      - name: Commit and push incoming
        run: |
          cd public
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add incoming/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated daily sync of private branches into incoming/ folder"
            git push origin main
          fi
